-- Final Working Schema - No IF NOT EXISTS for policies

-- Expense Accounts
CREATE TABLE IF NOT EXISTS expense_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Expenses
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES expense_accounts(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  category TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  amount DECIMAL(12, 2) NOT NULL,
  payment_method TEXT,
  owner_type TEXT CHECK (owner_type IN ('salesman', 'customer')),
  owner_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Salesmen
CREATE TABLE IF NOT EXISTS salesmen (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  area TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Expense Owners
CREATE TABLE IF NOT EXISTS expense_owners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT CHECK (type IN ('customer', 'salesman')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_expenses_account_id ON expenses(account_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(date);
CREATE INDEX IF NOT EXISTS idx_expense_accounts_active ON expense_accounts(is_active);

-- Enable RLS
ALTER TABLE expense_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE salesmen ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_owners ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "Enable all operations for expense_accounts" ON expense_accounts;
DROP POLICY IF EXISTS "Enable all operations for expenses" ON expenses;
DROP POLICY IF EXISTS "Enable all operations for salesmen" ON salesmen;
DROP POLICY IF EXISTS "Enable all operations for expense_owners" ON expense_owners;

-- Create new policies (without IF NOT EXISTS)
CREATE POLICY "Enable all operations for expense_accounts" ON expense_accounts
  USING (true) WITH CHECK (true);

CREATE POLICY "Enable all operations for expenses" ON expenses
  USING (true) WITH CHECK (true);

CREATE POLICY "Enable all operations for salesmen" ON salesmen
  USING (true) WITH CHECK (true);

CREATE POLICY "Enable all operations for expense_owners" ON expense_owners
  USING (true) WITH CHECK (true);
